### PR TITLE
feat:225 add support for callbacks before token expiration

### PR DESCRIPTION
**Pull request by jangolano**
@cecilia-sanare This is a first attempt at this.  You know JavaScript and the code a lot better than I do.  Feel free to comment, improve, etc.

### CODE REVIEW

**Comment by jangolano** [comment]
@davewoodward  Can you take a look at this?  Can this get merged today?

**Comment by cecilia-sanare** [comment]
A lot of this code already exists in `salte-auth`.

https://github.com/salte-io/salte-auth/blob/master/src/salte-auth.js#L667-L680

**All we need to do is the following:**

* add a `refresh` event
* make some minor tweaks to the `setTimeout` function so that `autoRefresh` still calls the refresh event
* add the ability to customize the `refreshToken` buffer (this is currently set to one minute)

**Something like the following should work:**

```js
  // ...
  $$refreshToken() {
    if (this.$timeouts.refresh !== undefined) {
      clearTimeout(this.$timeouts.refresh);
    }

    this.$timeouts.refresh = setTimeout(() => {
      // Allow Auto Refresh to be disabled.
      if (this.$config.autoRefresh) {
          this.refreshToken().catch((error) => {
            console.error(error);
          });
      }

      this.$fire('refresh');
      // We need to default `autoRefreshBuffer` to 60000 in the constructor.
    }, Math.max((this.profile.userInfo.exp * 1000) - Date.now() - this.$config.autoRefreshBuffer, 0));
  }
  // ...
```

Overall I think its a great idea! 
It allows developers to disable the `autoRefresh` functionality, while still giving them a hook into it!

**Comment by cecilia-sanare** [comment]
Just as a followup. Usage of the above would look like this.

```js
const auth = new SalteAuth({
  // ...
});

// This will happen post refresh, or when a refresh is requested if `autoRefresh` is disabled.
auth.on('refresh', () => {
  // Handle refresh logic here...
});
```

**Comment by cecilia-sanare** [comment]
Not entirely sure why this was closed as the functionality hasn't been implemented. 

I was just offering the code as a preferred implementation since 
I don't have time to write the tests for it right now.

**Comment by jangolano** [comment]
I am hoping to have an updated pull request for you today with the tests.

**Comment by kpitzen** [comment]
@cecilia-sanare We shouldn't still expect the refresh to bail, correct? What would you consider to be working test criteria for this feature?  Just that the token didn't refresh?

**Pull request closed without merging**
